# 系统配置 项目启动端口和模式
# @author zxl
system:
  host: "0.0.0.0"
  port: 5001
  env: debug
  # env: release

# logger 日志
logger:
  level: info
  prefix: '[gin-David-api]'
  director: logger
  show_line: true
  log_in_console: true

# mysql配置
mysql:
  host: "127.0.0.1"
  port: 3306
  db: gin-david
  username: root
  password: 123456
  log_level: dev
  charset: utf8
  maxIdle: 50
  maxOpen: 150
