definitions:
  model.AddSysMenuDto:
    properties:
      icon:
        type: string
      menuName:
        type: string
      menuStatus:
        type: integer
      menuType:
        type: integer
      parentId:
        type: integer
      sort:
        type: integer
      url:
        type: string
      value:
        type: string
    type: object
  result.Result:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回的数据
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact: {}
  description: 中央监护系统API接口文档
  title: 中央监护系统
  version: "1.0"
paths:
  /api/failed:
    get:
      description: 失败测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 失败测试
      tags:
      - 测试相关接口
  /api/success:
    get:
      description: 成功测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 成功测试
      tags:
      - 测试相关接口
  /api/sysMenu/add:
    post:
      description: 新增菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.AddSysMenuDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      tags:
      - 菜单相关接口
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
